import type { Resume } from "./types";

/**
 * Test data for adaptive scaling testing
 * Three variants: minimal, medium, maximum content
 */

// MINIMAL: Only basic information
export const minimalResume: Resume = {
  id: "test-minimal",
  personalDetails: {
    fullName: "John Doe",
    title: "Software Developer",
    email: "john.doe@email.com",
    phone: "+1 (555) 123-4567",
    location: "New York, NY",
    summary: "Passionate software developer with experience in web technologies.",
  },
  experience: [
    {
      id: "exp-001",
      position: "Software Developer",
      company: "Tech Company",
      location: "New York, NY",
      startDate: "2021-01",
      endDate: null,
      current: true,
      description: [
        "Developed web applications using React and Node.js",
        "Collaborated with team members on various projects",
      ],
    },
  ],
  education: [
    {
      id: "edu-001",
      institution: "University of Technology",
      degree: "Bachelor of Science",
      field: "Computer Science",
      location: "New York, NY",
      startDate: "2017-09",
      endDate: "2021-05",
      current: false,
    },
  ],
  skills: {
    skills: ["JavaScript", "React", "Node.js", "TypeScript", "Git"],
    tools: [],
    languages: [{ language: "English", proficiency: "Native" }],
  },
  certifications: [],
  projects: [],
  template: "classic",
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

// MEDIUM: Moderate amount of content
export const mediumResume: Resume = {
  id: "test-medium",
  personalDetails: {
    fullName: "Jane Smith",
    title: "Senior Software Engineer",
    email: "jane.smith@email.com",
    phone: "+1 (555) 234-5678",
    location: "San Francisco, CA",
    linkedin: "linkedin.com/in/jane-smith",
    github: "github.com/jane-smith",
    summary:
      "Results-driven Software Engineer with 5+ years of experience in full-stack development. Expertise in React, Node.js, and cloud technologies. Strong problem-solving skills and passion for building scalable applications.",
  },
  experience: [
    {
      id: "exp-001",
      position: "Senior Software Engineer",
      company: "Innovation Labs",
      location: "San Francisco, CA",
      startDate: "2021-06",
      endDate: null,
      current: true,
      description: [
        "Led development of microservices architecture serving 500K+ users",
        "Improved API performance by 35% through optimization techniques",
        "Mentored junior developers and conducted code reviews",
        "Implemented CI/CD pipeline reducing deployment time by 50%",
      ],
    },
    {
      id: "exp-002",
      position: "Software Engineer",
      company: "StartupHub",
      location: "Remote",
      startDate: "2019-03",
      endDate: "2021-05",
      current: false,
      description: [
        "Built RESTful APIs using Node.js and Express",
        "Developed responsive web applications with React and TypeScript",
        "Integrated third-party services including payment systems",
        "Participated in Agile development process",
      ],
    },
  ],
  education: [
    {
      id: "edu-001",
      institution: "Tech University",
      degree: "Master of Science",
      field: "Computer Science",
      location: "Boston, MA",
      startDate: "2017-09",
      endDate: "2019-05",
      current: false,
      achievements: [
        "GPA: 3.8/4.0",
        "Teaching Assistant for Web Development course",
      ],
    },
    {
      id: "edu-002",
      institution: "State University",
      degree: "Bachelor of Science",
      field: "Software Engineering",
      location: "Seattle, WA",
      startDate: "2013-09",
      endDate: "2017-05",
      current: false,
    },
  ],
  skills: {
    skills: [
      "JavaScript",
      "TypeScript",
      "React",
      "Node.js",
      "Express",
      "PostgreSQL",
      "MongoDB",
      "Docker",
      "AWS",
      "GraphQL",
      "REST API",
      "Agile",
    ],
    tools: ["Git", "GitHub", "Jira", "VS Code"],
    languages: [
      { language: "English", proficiency: "Native" },
      { language: "Spanish", proficiency: "Intermediate" },
    ],
  },
  certifications: [
    {
      id: "cert-001",
      name: "AWS Certified Developer - Associate",
      issuer: "Amazon Web Services",
      date: "2022-05",
      credentialId: "AWS-DEV-2022-001",
    },
  ],
  projects: [],
  template: "classic",
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

// MAXIMUM: All sections filled with extensive content
export const maximumResume: Resume = {
  id: "test-maximum",
  personalDetails: {
    fullName: "Alexandra Martinez Rodriguez",
    title: "Principal Software Architect & Technical Lead",
    email: "alexandra.martinez@email.com",
    phone: "+1 (555) 345-6789",
    location: "San Francisco, California",
    linkedin: "linkedin.com/in/alexandra-martinez-rodriguez",
    github: "github.com/alexandra-martinez",
    website: "alexandramartinez.dev",
    summary:
      "Highly accomplished Principal Software Architect with 12+ years of experience designing and implementing large-scale distributed systems. Deep expertise in microservices architecture, cloud infrastructure, and team leadership. Proven track record of leading cross-functional teams, driving technical innovation, and delivering enterprise solutions that serve millions of users. Passionate about mentoring developers and building scalable, maintainable systems.",
  },
  experience: [
    {
      id: "exp-001",
      position: "Principal Software Architect",
      company: "Global Tech Corporation",
      location: "San Francisco, CA",
      startDate: "2022-01",
      endDate: null,
      current: true,
      description: [
        "Architected and led migration of monolithic application to microservices architecture serving 5M+ daily active users across 50+ countries",
        "Reduced infrastructure costs by 45% through optimization of cloud resources and implementation of auto-scaling strategies",
        "Led technical design reviews and established architecture standards for engineering organization of 100+ developers",
        "Implemented distributed tracing and monitoring systems improving system observability and reducing MTTR by 60%",
        "Mentored senior engineers and conducted technical interviews for senior and staff-level positions",
        "Drove adoption of event-driven architecture patterns using Kafka and RabbitMQ for real-time data processing",
      ],
    },
    {
      id: "exp-002",
      position: "Senior Software Engineering Manager",
      company: "Enterprise Solutions Inc",
      location: "San Francisco, CA",
      startDate: "2019-03",
      endDate: "2021-12",
      current: false,
      description: [
        "Managed team of 15 engineers across three product areas, delivering critical features for enterprise customers",
        "Established engineering best practices including code review guidelines, testing standards, and deployment procedures",
        "Led API redesign initiative improving developer experience and reducing integration time by 70%",
        "Implemented comprehensive monitoring and alerting system achieving 99.95% uptime SLA",
        "Collaborated with product management to define technical roadmap and prioritize engineering initiatives",
      ],
    },
    {
      id: "exp-003",
      position: "Staff Software Engineer",
      company: "Innovative Tech Solutions",
      location: "Seattle, WA",
      startDate: "2016-06",
      endDate: "2019-02",
      current: false,
      description: [
        "Designed and implemented real-time analytics platform processing 10M+ events per day",
        "Built scalable data pipeline using Apache Spark and Kafka for ETL operations",
        "Led performance optimization efforts reducing query response time by 80%",
        "Established testing framework achieving 90% code coverage across critical services",
      ],
    },
    {
      id: "exp-004",
      position: "Senior Full-Stack Developer",
      company: "Digital Innovation Labs",
      location: "Austin, TX",
      startDate: "2013-01",
      endDate: "2016-05",
      current: false,
      description: [
        "Developed customer-facing applications using React, Redux, and Node.js serving 100K+ monthly users",
        "Implemented GraphQL API layer improving frontend development efficiency by 40%",
        "Integrated multiple payment gateways including Stripe, PayPal, and Braintree",
      ],
    },
  ],
  education: [
    {
      id: "edu-001",
      institution: "Massachusetts Institute of Technology",
      degree: "Master of Science",
      field: "Computer Science",
      location: "Cambridge, MA",
      startDate: "2011-09",
      endDate: "2013-06",
      current: false,
      achievements: [
        "Thesis: 'Scalable Distributed Systems for Real-Time Data Processing and Analytics'",
        "Research Assistant - Distributed Systems Lab, published 3 peer-reviewed papers",
        "Teaching Assistant for Advanced Algorithms and Distributed Systems courses",
        "GPA: 3.9/4.0, Dean's List all semesters",
      ],
    },
    {
      id: "edu-002",
      institution: "University of California, Berkeley",
      degree: "Bachelor of Science",
      field: "Computer Science and Engineering",
      location: "Berkeley, CA",
      startDate: "2007-09",
      endDate: "2011-05",
      current: false,
      achievements: [
        "Graduated Summa Cum Laude with Honors in Computer Science",
        "President of ACM Student Chapter, organized technical workshops and hackathons",
        "CalHacks 2010 Winner - Best Technical Innovation Award",
        "Undergraduate Researcher - Human-Computer Interaction Lab",
      ],
    },
  ],
  skills: {
    skills: [
      "System Architecture",
      "Microservices",
      "Distributed Systems",
      "Cloud Architecture",
      "JavaScript",
      "TypeScript",
      "Python",
      "Java",
      "Go",
      "React",
      "Next.js",
      "Node.js",
      "Express",
      "GraphQL",
      "REST API",
      "PostgreSQL",
      "MongoDB",
      "Redis",
      "Elasticsearch",
      "Kafka",
      "RabbitMQ",
      "Docker",
      "Kubernetes",
      "AWS",
      "Azure",
      "GCP",
      "Terraform",
      "CI/CD",
      "Jenkins",
      "GitHub Actions",
      "Technical Leadership",
      "Team Management",
      "Code Review",
      "Mentoring",
      "Agile",
      "Scrum",
      "System Design",
      "Performance Optimization",
    ],
    tools: [
      "Git",
      "GitHub",
      "GitLab",
      "Jira",
      "Confluence",
      "Figma",
      "VS Code",
      "IntelliJ IDEA",
      "Postman",
      "DataDog",
      "New Relic",
      "Grafana",
    ],
    languages: [
      { language: "English", proficiency: "Native" },
      { language: "Spanish", proficiency: "Native" },
      { language: "French", proficiency: "Professional" },
      { language: "Portuguese", proficiency: "Intermediate" },
    ],
  },
  certifications: [
    {
      id: "cert-001",
      name: "AWS Certified Solutions Architect - Professional",
      issuer: "Amazon Web Services",
      date: "2023-11",
      expiryDate: "2026-11",
      credentialId: "AWS-PSA-2023-9876",
      url: "https://aws.amazon.com/verification",
    },
    {
      id: "cert-002",
      name: "Certified Kubernetes Administrator (CKA)",
      issuer: "Cloud Native Computing Foundation",
      date: "2023-06",
      expiryDate: "2026-06",
      credentialId: "LF-CKA-2023-5432",
    },
    {
      id: "cert-003",
      name: "Google Cloud Professional Cloud Architect",
      issuer: "Google Cloud",
      date: "2022-09",
      expiryDate: "2025-09",
      credentialId: "GCP-PCA-2022-1234",
    },
    {
      id: "cert-004",
      name: "MongoDB Certified Developer Associate",
      issuer: "MongoDB University",
      date: "2021-12",
      credentialId: "MONGO-DEV-2021-7890",
    },
  ],
  projects: [],
  template: "classic",
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};
