import type { Resume } from "@/types";

/**
 * Mock resume data for testing and demonstration purposes
 * This data represents a complete resume with all sections filled
 */
export const mockResume: Resume = {
  id: "demo-resume-001",
  personalDetails: {
    fullName: "Sarah Anderson",
    title: "Senior Full-Stack Developer",
    email: "sarah.anderson@email.com",
    phone: "+1 (555) 234-5678",
    location: "San Francisco, CA",
    linkedin: "linkedin.com/in/sarah-anderson",
    github: "github.com/sarah-anderson",
    website: "sarahanderson.dev",
    photo: undefined,
    summary:
      "Results-driven Full-Stack Developer with 8+ years of experience building scalable web applications. Expertise in React, Node.js, and cloud technologies. Proven track record of leading development teams and delivering high-quality solutions that improve user experience and drive business growth.",
  },
  experience: [
    {
      id: "exp-001",
      position: "Senior Full-Stack Developer",
      company: "TechCorp Solutions",
      location: "San Francisco, CA",
      startDate: "2021-03",
      endDate: null,
      current: true,
      description: [
        "Led development of microservices architecture serving 2M+ daily active users",
        "Reduced API response time by 40% through optimization and caching strategies",
        "Mentored team of 5 junior developers, improving code quality and team velocity",
        "Implemented CI/CD pipeline reducing deployment time from 2 hours to 15 minutes",
        "Architected real-time notification system using WebSockets and Redis",
      ],
    },
    {
      id: "exp-002",
      position: "Full-Stack Developer",
      company: "StartupHub Inc",
      location: "Remote",
      startDate: "2018-06",
      endDate: "2021-02",
      current: false,
      description: [
        "Built RESTful APIs using Node.js and Express serving 500K+ requests daily",
        "Developed responsive React applications with TypeScript and Redux",
        "Integrated third-party payment systems (Stripe, PayPal) with 99.9% uptime",
        "Collaborated with designers to implement pixel-perfect UI components",
        "Established testing practices achieving 85% code coverage",
      ],
    },
    {
      id: "exp-003",
      position: "Junior Web Developer",
      company: "Digital Agency Pro",
      location: "Los Angeles, CA",
      startDate: "2016-01",
      endDate: "2018-05",
      current: false,
      description: [
        "Developed and maintained 20+ client websites using modern web technologies",
        "Implemented responsive designs ensuring cross-browser compatibility",
        "Optimized website performance achieving 90+ PageSpeed scores",
        "Collaborated with cross-functional teams in Agile environment",
      ],
    },
  ],
  education: [
    {
      id: "edu-001",
      institution: "Stanford University",
      degree: "Master of Science",
      field: "Computer Science",
      location: "Stanford, CA",
      startDate: "2014-09",
      endDate: "2016-06",
      current: false,
      gpa: "3.9",
      achievements: [
        "Thesis: 'Scalable Machine Learning Systems for Real-Time Data Processing'",
        "Teaching Assistant for Data Structures and Algorithms",
        "Dean's List - All Semesters",
      ],
    },
    {
      id: "edu-002",
      institution: "University of California, Berkeley",
      degree: "Bachelor of Science",
      field: "Software Engineering",
      location: "Berkeley, CA",
      startDate: "2010-09",
      endDate: "2014-05",
      current: false,
      gpa: "3.7",
      achievements: [
        "President of Computer Science Student Association",
        "Hackathon Winner - CalHacks 2013",
        "Graduated Cum Laude",
      ],
    },
  ],
  skills: {
    technical: [
      "JavaScript/TypeScript",
      "React",
      "Next.js",
      "Node.js",
      "Express",
      "Python",
      "Django",
      "PostgreSQL",
      "MongoDB",
      "Redis",
      "Docker",
      "Kubernetes",
      "AWS",
      "Azure",
      "Git",
      "CI/CD",
      "GraphQL",
      "REST APIs",
      "Microservices",
      "TDD/BDD",
    ],
    languages: [
      { language: "English", proficiency: "Native" },
      { language: "Spanish", proficiency: "Professional" },
      { language: "French", proficiency: "Intermediate" },
    ],
    soft: [
      "Team Leadership",
      "Agile/Scrum",
      "Problem Solving",
      "Communication",
      "Code Review",
    ],
  },
  certifications: [
    {
      id: "cert-001",
      name: "AWS Certified Solutions Architect - Professional",
      issuer: "Amazon Web Services",
      date: "2023-08",
      expiryDate: "2026-08",
      credentialId: "AWS-PSA-2023-001234",
      url: "https://aws.amazon.com/verification",
    },
    {
      id: "cert-002",
      name: "Certified Kubernetes Administrator (CKA)",
      issuer: "Cloud Native Computing Foundation",
      date: "2022-11",
      expiryDate: "2025-11",
      credentialId: "LF-CKA-2022-567890",
      url: "https://training.linuxfoundation.org/certification/verify",
    },
    {
      id: "cert-003",
      name: "MongoDB Certified Developer",
      issuer: "MongoDB University",
      date: "2021-06",
      credentialId: "MONGO-DEV-2021-987654",
    },
  ],
  projects: [
    {
      id: "proj-001",
      name: "E-Commerce Platform",
      description:
        "Full-stack e-commerce solution with real-time inventory management, payment processing, and admin dashboard. Built with Next.js, Node.js, PostgreSQL, and Redis. Handles 10K+ daily transactions.",
      technologies: [
        "Next.js",
        "TypeScript",
        "Node.js",
        "PostgreSQL",
        "Redis",
        "Stripe",
        "Docker",
      ],
      url: "https://ecommerce-demo.example.com",
      githubUrl: "https://github.com/sarah-anderson/ecommerce-platform",
      startDate: "2023-01",
      endDate: "2023-09",
    },
    {
      id: "proj-002",
      name: "Task Management SaaS",
      description:
        "Collaborative task management application with real-time updates, team workspaces, and advanced analytics. Serves 5000+ active users with 99.9% uptime.",
      technologies: [
        "React",
        "TypeScript",
        "GraphQL",
        "Node.js",
        "MongoDB",
        "WebSocket",
        "AWS",
      ],
      url: "https://taskmanager.example.com",
      githubUrl: "https://github.com/sarah-anderson/task-manager",
      startDate: "2022-03",
      endDate: "2022-12",
    },
    {
      id: "proj-003",
      name: "Open Source Design System",
      description:
        "Comprehensive React component library with TypeScript support, accessibility features, and Storybook documentation. 2000+ GitHub stars.",
      technologies: [
        "React",
        "TypeScript",
        "Storybook",
        "Tailwind CSS",
        "Jest",
        "Rollup",
      ],
      githubUrl: "https://github.com/sarah-anderson/design-system",
      startDate: "2021-06",
    },
  ],
  template: "classic",
  createdAt: "2024-01-01T00:00:00.000Z",
  updatedAt: "2024-01-01T00:00:00.000Z",
};

/**
 * Minimal resume data for testing empty states
 */
export const emptyResume: Resume = {
  id: "empty-resume-001",
  personalDetails: {
    fullName: "",
    title: "",
    email: "",
    phone: "",
  },
  experience: [],
  education: [],
  skills: {
    technical: [],
    languages: [],
  },
  certifications: [],
  projects: [],
  template: "classic",
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};
